stages:
  - kotlin_build
  - kotlin_test
  - dokka_publish
  - docs_build
  - docs_test
  - docs_publish
  - kotlin_publish

variables:
  WRITERSIDE_BUILDER_VERSION: "242.21870"
  UBUNTU_IMAGE: "ubuntu:latest"

kotlin_build:
  image: ${UBUNTU_IMAGE}
  stage: kotlin_build
  before_script:
    - apt-get update -y  && apt upgrade -y
    - apt install curl gcc -y
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source ~/.bashrc
  script:
    - ./gradlew clean build dokkaHtmlMultiModule -x check -x allTests -x test
  artifacts:
    expire_in: 10 days
    paths:
      - build/dokka/htmlMultiModule
