services:
  keycloak:
    container_name: keycloak-mokt
    image: quay.io/keycloak/keycloak:latest
    restart: no
    ports:
      - "8080:8080"
    environment:
      # All passwords and keys are test only. Don't use in production!!!
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 200M
        limits:
          cpus: "0.9"
          memory: 500M
    volumes:
      - keycloak:/opt/keycloak/data
    networks:
      - keycloak

volumes:
  keycloak:
    driver: local

networks:
  keycloak:
    driver: bridge