name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  pages:
    uses: ./.github/workflows/dokka.yml
    if: github.ref == 'refs/heads/main'
    needs:
      - build
